### ISSUE TITLE
The readme documentation has incorrect code for file upload 

### ISSUE THREAD

**Issue by chinmaycdj** [DolbyIO/dolbyio-rest-apis-client-node#47]
In the section **Upload a file for processing** in README 

` await dolbyio.io.uploadFile(jwt, inputUrl, originalFilePath);
`
Should actually be 

`await dolbyio.media.io.uploadFile(jwt, inputUrl, originalFilePath);
`

**Comment by FabienLavocat** [comment]
You're absolutely right, thanks for catching that!
